# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac3ae345f43648e5fc46a43ed1e47ddae6831c0d5551e7094b19cb3e8f5ec926d3f4a7972cb1c47695a9a70eef6b1e3a612d88aa078b95ece567580327c3be5e

test:
  secret_key_base: cbbe461006bbb2763022167aecc1af19e302ca8d4694260f0906c2957b2bda4f01b44c753002063907cf5e1408e2d4fed750dad4d48adeb7ae3d63857c3ffe9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
